package com.hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.hello.User;
import com.hello.Level;
import com.hello.UserRepository;
import com.hello.LevelRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/hello") // This means URL's start with /hello (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    private LevelRepository levelRepository;

    @GetMapping(path="/adduser") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/addlevel") // Map ONLY GET Requests
    public @ResponseBody String addNewLevel (@RequestParam String name
            , @RequestParam String description) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Level n = new Level();
        n.setName(name);
        n.setName(description);
        levelRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/allusers")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/alllevels")
    public @ResponseBody Iterable<Level> getAllLevels() {
        // This returns a JSON or XML with the users
        return levelRepository.findAll();
    }
}
